package com.example.military.rules

import com.example.military.TaktinioVertinimoModelis;

rule "Rule00: Tikriname ar modelis yra"
when
    $model: TaktinioVertinimoModelis()
then
    System.out.println("Drools taisykle: Modelis yra.");
end

rule "Rule01: Ar visos atasakaitos yra"
when
    $model: TaktinioVertinimoModelis( duomenys.radaroSignalai != null && duomenys.zvalgybosAtaskaita != null && duomenys.laukoStebejimas != null )
then
    System.out.println("Drools taisykle: Visos ataskaitos yra.");
end

rule "Rule02: Nera bent vienos ataskaitos"
when
    $model: TaktinioVertinimoModelis( duomenys.radaroSignalai == null || duomenys.zvalgybosAtaskaita == null || duomenys.laukoStebejimas == null )
then
    System.out.println("Drools taisykle: Nera bent vienos ataskaitos.");
end

// aukstas, vidutinis, zemas
rule "Rule03: Patikrink aukštą grėsmę"
when
    $model: TaktinioVertinimoModelis( duomenys.radaroSignalai != null && duomenys.radaroSignalai.contains("aukstas") )
then
    System.out.println("Drools taisykle: Auksta gresme nustatyta.");
end

rule "Rule04: Patikrink vidutinę grėsmę"
when
    $model: TaktinioVertinimoModelis( duomenys.radaroSignalai != null && duomenys.radaroSignalai.contains("vidutinis") )
then
    System.out.println("Drools taisykle: Vidutine gresme nustatyta.");
end

rule "Rule05: Patikrink žemą grėsmę"
when
    $model: TaktinioVertinimoModelis( duomenys.radaroSignalai != null && duomenys.radaroSignalai.contains("zemas") )
then
    System.out.println("Drools taisykle: Zema gresme nustatyta.");
end

// kritine, rimta, normali
rule "Rule06: Zvalgybos analize kritine"
when
    $model: TaktinioVertinimoModelis( duomenys.zvalgybosAtaskaita != null && duomenys.zvalgybosAtaskaita.contains("kritine") )
then
    System.out.println("Drools taisykle: zvalgybos ataskaita kritine.");
end

rule "Rule07: Zvalgybos analize rimta"
when
    $model: TaktinioVertinimoModelis( duomenys.zvalgybosAtaskaita != null && duomenys.zvalgybosAtaskaita.contains("rimta") )
then
    System.out.println("Drools taisykle: zvalgybos ataskaita rimta.");
end

rule "Rule08: Zvalgybos analize normali" 
when
    $model: TaktinioVertinimoModelis( duomenys.zvalgybosAtaskaita != null && duomenys.zvalgybosAtaskaita.contains("normali") )
then
    System.out.println("Drools taisykle: zvalgybos ataskaita normali.");
end

// pavojinga, nestabili, rami
rule "Rule09: Lauko stebejimas pavojinga"
when
    $model: TaktinioVertinimoModelis( duomenys.laukoStebejimas != null && duomenys.laukoStebejimas.contains("pavojinga") )
then
    System.out.println("Drools taisykle: lauko stebejimas pavojingas.");
end

rule "Rule10: Lauko stebejimas nestabili"
when
    $model: TaktinioVertinimoModelis( duomenys.laukoStebejimas != null && duomenys.laukoStebejimas.contains("nestabili") )
then
    System.out.println("Drools taisykle: lauko stebejimas nestabilus.");
end

rule "Rule11: Lauko stebejimas rami" 
when
    $model: TaktinioVertinimoModelis( duomenys.laukoStebejimas != null && duomenys.laukoStebejimas.contains("rami") )
then
    System.out.println("Drools taisykle: lauko stebejimas yra ramus.");
end

// vertejimoRezultatas: labai aukstas, aukstas, vidutinis, zemas, labai zemas
rule "Rule12: Vertejimo rezultatas labai aukštas"
when
    $model: TaktinioVertinimoModelis(vertejimoRezultatas.contains("Labai aukstas gresmes lygis."))
then
    System.out.println("Drools taisykle: Vertinimo rezultatas labai aukstas.");
end

rule "Rule13: Vertejimo rezultatas aukštas"
when
    $model: TaktinioVertinimoModelis(vertejimoRezultatas.contains("Aukstas gresmes lygis"))
then
    System.out.println("Drools taisykle: Vertinimo rezultatas aukstas.");
end

rule "Rule14: Vertejimo rezultatas vidutinis"
when
    $model: TaktinioVertinimoModelis(vertejimoRezultatas.contains("Vidutinis gresmes lygis"))
then
    System.out.println("Drools taisykle: Vertinimo rezultatas vidutinis.");
end

rule "Rule15: Vertejimo rezultatas žemas"
when
    $model: TaktinioVertinimoModelis(vertejimoRezultatas.contains("Zemas gresmes lygis"))
then
    System.out.println("Drools taisykle: Vertinimo rezultatas zemas.");
end

rule "Rule16: Vertejimo rezultatas labai žemas"
when
    $model: TaktinioVertinimoModelis(vertejimoRezultatas.contains("Labai zemas gresmes lygis"))
then
    System.out.println("Drools taisykle: Vertinimo rezultatas labai zemas.");
end